server:
  port: 8080


spring:
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa.hibernate.ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/card_manager

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type: TRACE

spring.servlet.multipart.max-file-size: 5MB
spring.servlet.multipart.max-request-size: 5MB



appConf:
  rabbitHost: localhost
  transferMessageText: Transfer successfully done!

